from Aurora import (DEV_USERS, DRAGONS, DEMONS, TIGERS, WOLVES, telethn)

KACCHAN = [5989692316]

IMMUNE_USERS = DRAGONS + WOLVES + DEMONS + TIGERS + DEV_USERS + ISHIKKI

IMMUNE_USERS = list(DRAGONS) + list(WOLVES) + list(DEMONS) + list(
    TIGERS) + list(DEV_USERS) + list(KACCHAN)
